/**
 * EventRepository.java
 *
 * Repository class responsible for all Firestore operations related to events.
 * Implements the Repository pattern to abstract data access from the UI layer.
 * All methods are asynchronous — results are delivered via callback interfaces.
 *
 */
package com.example.CampusEventDiscovery.repository;

import android.util.Log;

import com.example.CampusEventDiscovery.model.Event;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.Query;

import java.util.ArrayList;
import java.util.List;

/**
 * Handles all read and write operations for the Firestore 'events' collection.
 * All Firestore calls include both success and failure listeners.
 */
public class EventRepository {

    private static final String TAG = EventRepository.class.getSimpleName();
    private static final String COLLECTION = "events";
    private final FirebaseFirestore db = FirebaseFirestore.getInstance();

    /**
     * Adds a new event document to the Firestore 'events' collection.
     * The document ID is auto-generated by Firestore and set back on the Event object.
     *
     * @param event    The Event object to write to Firestore.
     * @param callback Called with onSuccess(event) if write succeeds,
     *                 onFailure(e) if the write fails.
     */
    public void addEvent(Event event, EventCallback callback) {
        db.collection(COLLECTION)
                .add(event)
                .addOnSuccessListener(documentReference -> {
                    event.setEventId(documentReference.getId());
                    callback.onSuccess(event);
                })
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Failed to add event", e);
                    callback.onFailure(e);
                });
    }

    /**
     * Fetches all approved events from Firestore ordered by dateTime ascending.
     * Only returns events where isApproved is true and status is active.
     *
     * @param callback Called with onSuccess(List) containing all active approved events,
     *                 or onFailure(e) if the query fails.
     */
    public void getEvents(EventListCallback callback) {
        db.collection(COLLECTION)
                .whereEqualTo("isApproved", true)
                .whereEqualTo("status", "active")
                .orderBy("dateTime", Query.Direction.ASCENDING)
                .get()
                .addOnSuccessListener(querySnapshot -> {
                    List<Event> events = new ArrayList<>();
                    for (DocumentSnapshot doc : querySnapshot.getDocuments()) {
                        Event event = doc.toObject(Event.class);
                        if (event != null) {
                            event.setEventId(doc.getId());
                            events.add(event);
                        }
                    }
                    callback.onSuccess(events);
                })
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Failed to fetch events", e);
                    callback.onFailure(e);
                });
    }

    /**
     * Fetches a single event document from Firestore by its document ID.
     *
     * @param id       The Firestore document ID of the event to fetch.
     * @param callback Called with onSuccess(event) if the document exists,
     *                 onFailure(e) if not found or query fails.
     */
    public void getEventById(String id, EventCallback callback) {
        db.collection(COLLECTION)
                .document(id)
                .get()
                .addOnSuccessListener(documentSnapshot -> {
                    if (documentSnapshot.exists()) {
                        Event event = documentSnapshot.toObject(Event.class);
                        if (event != null) event.setEventId(documentSnapshot.getId());
                        callback.onSuccess(event);
                    } else {
                        callback.onFailure(new Exception("Event not found"));
                    }
                })
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Failed to fetch event by ID: " + id, e);
                    callback.onFailure(e);
                });
    }

    /**
     * Updates an existing event document in Firestore.
     * Uses the eventId field on the Event object to locate the document.
     *
     * @param event    The Event object containing updated field values.
     * @param callback Called with onSuccess(event) if update succeeds,
     *                 onFailure(e) if the update fails.
     */
    public void updateEvent(Event event, EventCallback callback) {
        db.collection(COLLECTION)
                .document(event.getEventId())
                .set(event)
                .addOnSuccessListener(unused -> callback.onSuccess(event))
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Failed to update event: " + event.getEventId(), e);
                    callback.onFailure(e);
                });
    }

    /**
     * Deletes an event document from Firestore by its document ID.
     *
     * @param id       The Firestore document ID of the event to delete.
     * @param callback Called with onSuccess(null) if deletion succeeds,
     *                 onFailure(e) if the deletion fails.
     */
    public void deleteEvent(String id, EventCallback callback) {
        db.collection(COLLECTION)
                .document(id)
                .delete()
                .addOnSuccessListener(unused -> callback.onSuccess(null))
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Failed to delete event: " + id, e);
                    callback.onFailure(e);
                });
    }
}